name: 'Setup latest npm'

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
      with:
        node-version: 'lts/*'

    - name: Install latest npm
      run: |
        echo "Current npm version: $(npm -v)"
        npm install -g npm@latest
        echo "Updated npm version: $(npm -v)"
      shell: sh
